services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqltodo
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQLDB_USER}
      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
    ports:
      - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p${MYSQLDB_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 35s
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: todoapp
    depends_on:
      mysqldb:
        condition: service_healthy   
    ports:
      - ${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}
    env_file: ./.env                 

volumes:
  mysql_data: